"""Initial schema: users, venues, checkins

Revision ID: 50a654c32b1f
Revises:
Create Date: 2025-10-25 19:52:00.295125

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50a654c32b1f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("netid", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("anonymize_checkins", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_active_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_netid"), "users", ["netid"], unique=True)
    op.create_table(
        "venues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("amenities", sa.JSON(), nullable=True),
        sa.Column("accessibility", sa.JSON(), nullable=True),
        sa.Column("opening_hours", sa.JSON(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_venues_category"), "venues", ["category"], unique=False)
    op.create_index(op.f("ix_venues_id"), "venues", ["id"], unique=False)
    op.create_index(op.f("ix_venues_name"), "venues", ["name"], unique=False)
    op.create_table(
        "checkins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("occupancy", sa.Integer(), nullable=False),
        sa.Column("noise", sa.Integer(), nullable=False),
        sa.Column("anonymous", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checkins_created_at"), "checkins", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_checkins_id"), "checkins", ["id"], unique=False)
    op.create_index(op.f("ix_checkins_user_id"), "checkins", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_checkins_venue_id"), "checkins", ["venue_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_checkins_venue_id"), table_name="checkins")
    op.drop_index(op.f("ix_checkins_user_id"), table_name="checkins")
    op.drop_index(op.f("ix_checkins_id"), table_name="checkins")
    op.drop_index(op.f("ix_checkins_created_at"), table_name="checkins")
    op.drop_table("checkins")
    op.drop_index(op.f("ix_venues_name"), table_name="venues")
    op.drop_index(op.f("ix_venues_id"), table_name="venues")
    op.drop_index(op.f("ix_venues_category"), table_name="venues")
    op.drop_table("venues")
    op.drop_index(op.f("ix_users_netid"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
